spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockmanagementdb?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
#  redis:
#    host: localhost
#    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: org.axr.model
#  configuration:
#    map-underscore-to-camel-case: true

logging:
  level:
    com.alicp.jetcache: debug


jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 100
      expireAfterWriteInMillis: 60000 # 1 分钟
  remote:
    default:
      type: redis
      host: localhost
      port: 6379
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      expireAfterWriteInMillis: 180000 # 3 分钟
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50

